# Generated by Django 3.0.3 on 2020-03-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='author_obj',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='publish',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='visibilities',
            new_name='visibility',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='visible_to',
            new_name='visibleTo',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
