# Generated by Django 3.0.3 on 2020-04-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='contentType',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
