# Generated by Django 3.0.3 on 2020-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.TextField(blank=True, default='PUBLIC', max_length=300),
        ),
    ]
