# Generated by Django 3.0.3 on 2020-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.URLField(max_length=300, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
