# Generated by Django 3.0.3 on 2020-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200323_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibleTo',
            field=models.TextField(blank=True),
        ),
    ]
