# Generated by Django 3.0.3 on 2020-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
