# Generated by Django 3.0.3 on 2020-03-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
