# Generated by Django 3.0.3 on 2020-03-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200325_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='visibleTo',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
