# Generated by Django 3.0.3 on 2020-03-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_posts_author'),
        ('posts', '0002_auto_20200323_2003'),
    ]

    operations = [
    ]
