# Generated by Django 3.0.3 on 2020-03-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200325_0410'),
        ('posts', '0005_merge_20200324_0947'),
    ]

    operations = [
    ]
