# Generated by Django 3.0.3 on 2020-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_merge_20200325_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='origin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
