# Generated by Django 2.1.5 on 2020-03-05 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plainText', models.TextField()),
                ('title', models.TextField()),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('test', models.TextField(blank=True, default='test')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Posts')),
            ],
        ),
    ]
