# Generated by Django 3.0.3 on 2020-04-04 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth', models.TextField()),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Posts')),
            ],
        ),
    ]
