# Generated by Django 2.1.5 on 2020-03-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='auth',
        ),
    ]
