# Generated by Django 2.1.5 on 2020-03-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='plainText',
            new_name='auth',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='test',
        ),
    ]
