# Generated by Django 3.0.3 on 2020-03-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='publish',
            new_name='published',
        ),
    ]
