# Generated by Django 3.0.3 on 2020-04-02 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='auth',
        ),
        migrations.AddField(
            model_name='comments',
            name='auth_id',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comments',
            name='github',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comments',
            name='host',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comments',
            name='url',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
