# Generated by Django 2.1.5 on 2020-03-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='test',
            field=models.TextField(blank=True, default='test'),
        ),
    ]
