# Generated by Django 3.0.3 on 2020-04-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200402_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
