# Generated by Django 2.1.5 on 2020-03-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200304_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Posts'),
        ),
    ]
