# Generated by Django 2.1.5 on 2020-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200304_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='root',
            field=models.TextField(),
        ),
    ]
