# Generated by Django 2.1.5 on 2020-03-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200304_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Posts'),
        ),
    ]
