# Generated by Django 3.0.3 on 2020-03-23 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.URLField()),
                ('receiver', models.URLField()),
                ('status', models.BooleanField(default=None, null=True)),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.RemoveField(
            model_name='friendrequests',
            name='authorID',
        ),
        migrations.RemoveField(
            model_name='friendrequests',
            name='friendID',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='author',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='FriendRequests',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
