# Generated by Django 3.0.3 on 2020-03-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequests',
            name='authorID',
        ),
        migrations.RemoveField(
            model_name='friendrequests',
            name='friendID',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='author',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.AlterField(
            model_name='following',
            name='receiver',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='following',
            name='sender',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='FriendRequests',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
